/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsAuctionUuidRouteRouteImport } from './routes/auctions/$auctionUuid/route'
import { Route as AuctionsAuctionUuidIndexRouteImport } from './routes/auctions/$auctionUuid/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsAuctionUuidRouteRoute =
  AuctionsAuctionUuidRouteRouteImport.update({
    id: '/auctions/$auctionUuid',
    path: '/auctions/$auctionUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuctionsAuctionUuidIndexRoute =
  AuctionsAuctionUuidIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuctionsAuctionUuidRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRouteRouteWithChildren
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions/$auctionUuid': typeof AuctionsAuctionUuidRouteRouteWithChildren
  '/auctions/$auctionUuid/': typeof AuctionsAuctionUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auctions/$auctionUuid' | '/auctions/$auctionUuid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auctions/$auctionUuid'
  id: '__root__' | '/' | '/auctions/$auctionUuid' | '/auctions/$auctionUuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsAuctionUuidRouteRoute: typeof AuctionsAuctionUuidRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid': {
      id: '/auctions/$auctionUuid'
      path: '/auctions/$auctionUuid'
      fullPath: '/auctions/$auctionUuid'
      preLoaderRoute: typeof AuctionsAuctionUuidRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions/$auctionUuid/': {
      id: '/auctions/$auctionUuid/'
      path: '/'
      fullPath: '/auctions/$auctionUuid/'
      preLoaderRoute: typeof AuctionsAuctionUuidIndexRouteImport
      parentRoute: typeof AuctionsAuctionUuidRouteRoute
    }
  }
}

interface AuctionsAuctionUuidRouteRouteChildren {
  AuctionsAuctionUuidIndexRoute: typeof AuctionsAuctionUuidIndexRoute
}

const AuctionsAuctionUuidRouteRouteChildren: AuctionsAuctionUuidRouteRouteChildren =
  {
    AuctionsAuctionUuidIndexRoute: AuctionsAuctionUuidIndexRoute,
  }

const AuctionsAuctionUuidRouteRouteWithChildren =
  AuctionsAuctionUuidRouteRoute._addFileChildren(
    AuctionsAuctionUuidRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsAuctionUuidRouteRoute: AuctionsAuctionUuidRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
